### ISSUE TITLE
AR hit test not working in Chrome Canary 79.0.3919.0

### ISSUE THREAD

**Issue by faaaaabi** [immersive-web/webxr-samples#40]
The hit test in the _phone-ar-hit-test.html_ proposal seems to be broken. Following Error occurs:

```
Uncaught (in promise) TypeError: Failed to execute 'requestHitTest' on 'XRSession': parameter 1 is not of type 'XRRay'.
    at XRSession.onXRFrame (phone-ar-hit-test.html:214)
```

**Comment by bialpio** [comment]
Thanks for the report! Both the hit test API and Chrome's implementation of it are still in flux. Chrome has a prototype (outdated) implementation of the API as described [here](https://github.com/immersive-web/hit-test/blob/master/explainer.md) and the sample pages are passing different parameters. I'll try to issue a PR to address it since it will be a small change, but I don't know if we should expect that this repo will be kept up to date with features that are not yet parts of of the main WebXR spec.

**Comment by faaaaabi** [comment]
All right, I see. Thanks for the explanation.  
Can confirm that it's working now. Thanks a lot
