### ISSUE TITLE
Gltf2Node issue on *.glb files

### ISSUE THREAD

**Issue by buddyspencer** [immersive-web/webxr-samples#56]
Hi to all,
I tried the sunflower example and it works, but if I replace the .gltf file with another file but with extension *.glb it doesn't works. The glb file used is version 2.

Thank you :)

**Comment by klausw** [comment]
FYI, the "cottontail" renderer used for these samples doesn't necessarily support features beyond what's specifically needed in them, and I'm not sure if @toji has any specific plans to take it beyond that. GLTF is a complex format when including extensions and advanced rendering. Consider using a library such as three.js which has more complete support, or a framework building on that such as A-Frame if you want to get started quickly?

**Comment by toji** [comment]
@klaus is correct in that the rendering library for the samples (previously referred to as "cottontail") is not intended to be a general purpose framework, and as such are lacking in many features that developers may want in a mature library. I highly suggest looking for other solutions like Three.js or A-Frame, and I know that other libraries are in the process of adding XR support.

That said, I do want to support *.glb files, mostly so that I can create some samples that make use of the assets in the [webxr-input-profiles](https://github.com/immersive-web/webxr-input-profiles). I don't have any specific timeline for when that may happen, though, and even once it is added I don't recommend using that code for your own projects. As such, I'm closing this issue.
